//> using toolkit typelevel:latest
//> using packaging.output "dawnctl"
//> using nativeMode "release-fast"
//> using dep io.circe::circe-core:0.14.6
//> using dep io.circe::circe-parser:0.14.6
//> using dep io.circe::circe-generic:0.14.6
//> using dep com.lihaoyi::os-lib:0.9.1
//> using dep com.nimbusds:nimbus-jose-jwt:9.31
//> using dep org.bouncycastle:bcprov-jdk15on:1.70
//> using dep org.bouncycastle:bcpkix-jdk15on:1.70
//> using dep net.i2p.crypto:eddsa:0.3.0
