//> using scala 3.3.1
//> using toolkit typelevel:latest
//> using packaging.output "dawnctl"
//> using nativeMode "release-fast"
//> using dep io.circe::circe-core:0.14.6
//> using dep io.circe::circe-parser:0.14.6
//> using dep io.circe::circe-generic:0.14.6
//> using dep com.lihaoyi::os-lib:0.9.1
//> using dep com.nimbusds:nimbus-jose-jwt:9.35
//> using dep com.google.crypto.tink:tink:1.11.0
//> using dep org.bouncycastle:bcprov-jdk15on:1.70
//> using dep org.bouncycastle:bcpkix-jdk15on:1.70
//> using dep com.google.zxing:core:3.5.2
//> using dep com.softwaremill.sttp.client3::core:3.9.0
//> using dep com.softwaremill.sttp.client3::circe:3.9.0
//> using dep com.softwaremill.sttp.client3::async-http-client-backend-cats:3.9.0
//> using dep org.slf4j:slf4j-nop:2.0.9 
///> using dep com.apicatalog:iron-ed25519-cryptosuite-2020:0.8.1
